career/urls.py
from django.urls import path

from career import views

app_name = 'career'

urlpatterns = []

urlpatterns += (
    # urls for JobApplication
    path('job-application/', views.JobApplicationListView.as_view(), name='job-application-list'),
    path('job-application/create/', views.JobApplicationCreateView.as_view(), name='job-application-create'),
    path('job-application/detail/<str:slug>/', views.JobApplicationDetailView.as_view(), name='job-application-detail'),
    path('job-application/update/<str:slug>/', views.JobApplicationUpdateView.as_view(), name='job-application-update'),
    path('job-application/delete/<str:slug>/', views.JobApplicationDeleteView.as_view(), name='job-application-delete')
)

urlpatterns += (
    # urls for JobPosting
    path('job-posting/', views.JobPostingListView.as_view(), name='job-posting-list'),
    path('job-posting/create/', views.JobPostingCreateView.as_view(), name='job-posting-create'),
    path('job-posting/detail/<str:slug>/', views.JobPostingDetailView.as_view(), name='job-posting-detail'),
    path('job-posting/update/<str:slug>/', views.JobPostingUpdateView.as_view(), name='job-posting-update'),
    path('job-posting/delete/<str:slug>/', views.JobPostingDeleteView.as_view(), name='job-posting-delete')
)

tsa/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static

from tsa import settings
from achievement.urls import urlpatterns as achievement_urls
from career.urls import urlpatterns as career_urls
from mentorship.urls import urlpatterns as mentoring_urls
from profile_management.urls import urlpatterns as profile_management_urls
from social_network.urls import urlpatterns as social_urls
from util.registration import urlpatterns as registration_urls
from util.site import urlpatterns as site_urls
from util.urls import urlpatterns as util_urls
from volunteer.urls import urlpatterns as volunteer_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(site_urls + registration_urls)),
    path('mentorship/', include((mentoring_urls, 'mentorship'))),
    path('util/', include((util_urls, 'util'))),
    path('achievement/', include((achievement_urls, 'achievement'))),
    path('career/', include((career_urls, 'career'))),
    path('profile_management/', include((profile_management_urls, 'profile_management'))),
    path('social_network/', include((social_urls, 'social_network'))),
    path('volunteer/', include((volunteer_urls, 'volunteer'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

career/models.py
import datetime as dt

from django.contrib.contenttypes.fields import GenericRelation
from django.db import models

from util import current_timezone
from util.models import text_default, name_default, datetime_default, SoftDeleteMixin


class JobPosting(SoftDeleteMixin):
    title = models.CharField(**name_default)
    description = models.TextField(**text_default)
    source = models.ForeignKey('util.BaseUser', on_delete=models.DO_NOTHING,
                               related_name='job_postings')
    min_work_experience = models.PositiveSmallIntegerField()
    is_volunteer_job = models.BooleanField(default=False)
    approvals = GenericRelation('util.Approval', related_name='job_postings')
    required_qualification = models.CharField(**name_default)
    required_qualification_description = models.TextField()

    def publish(self, **kwargs):
        self.excluded_broadcasts = ['approvals']
        return super(JobPosting, self).publish(**kwargs)


class JobApplication(SoftDeleteMixin):
    job_posting = models.ForeignKey('JobPosting', on_delete=models.DO_NOTHING, related_name='job_applications')
    application_cv = models.ForeignKey('profile_management.UserCV', related_name='job_application',
                                       on_delete=models.DO_NOTHING)
    application_reason = models.TextField(**text_default)
    application_datetime = models.DateTimeField(**datetime_default)

    def save(self, *args, **kwargs):
        if not self.application_datetime:
            self.application_datetime = current_timezone(dt.datetime.now())

    def publish(self, **kwargs):
        # Job applications can be viewed on career management but not user's wall
        return NotImplemented

career/forms.py
from django import forms
from career import models


class JobApplicationForm(forms.ModelForm):

    def get_initial_for_field(self, field, field_name):
        # override the initial value for the specified form field
        return super(JobApplicationForm, self).get_initial_for_field(field, field_name)

    class Meta:
        model = models.JobApplication
        exclude = ['application_datetime']
        fields = ['job_posting', 'application_cv', 'application_reason', 'is_public', 'is_shareable']

    def save(self, commit=True):
        pass


class JobPostingForm(forms.ModelForm):

    def get_initial_for_field(self, field, field_name):
        # override the initial value for the specified form field
        return super(JobPostingForm, self).get_initial_for_field(field, field_name)

    class Meta:
        model = models.JobPosting
        fields = '__all__'
        exclude = ['source']

career/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import ModelMultipleChoiceField
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView, UpdateView, CreateView

from career import forms
from career import models
from profile_management.models import UserCV
from util.views import DeleteAclMixin, UpdateAclMixin


class JobApplicationListView(LoginRequiredMixin, ListView):
    model = models.JobApplication
    # paginate_by = 10
    template_name = 'career/job_application_list.html'
    login_url = reverse_lazy('user-login')

    def get_queryset(self):
        # Retrieve list object for the current user or approved user  
        user = self.request.user
        if user.is_authenticated:
            queryset = super(JobApplicationListView, self).get_queryset()
            # filter queryset for logged in user
            queryset = queryset.filter(application_cv__user=user)
            return queryset
        else:
            return super(JobApplicationListView, self).get_queryset().none()


class JobApplicationCreateView(LoginRequiredMixin, CreateView):
    model = models.JobApplication
    form_class = forms.JobApplicationForm
    template_name = 'career/job_application_form.html'
    initial = {}
    login_url = reverse_lazy('user-login')

    def get(self, request, *args, **kwargs):        
        queryset = UserCV.objects.filter(user=self.request.user)
        form = self.form_class(initial={'application_cv': queryset})
        form.fields['application_cv'] = ModelMultipleChoiceField(queryset)
        return render(request, template_name=self.template_name, context={'form': form})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        initial = super(JobApplicationCreateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('career:job_application-list')


class JobApplicationDetailView(LoginRequiredMixin, DetailView):
    model = models.JobApplication
    template_name = 'career/job_application_detail.html'
    login_url = reverse_lazy('user-login')

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(JobApplicationDetailView, self).get_context_data(**kwargs)


class JobApplicationUpdateView(UpdateAclMixin):
    model = models.JobApplication
    form_class = forms.JobApplicationForm
    template_name = 'career/job_application_form.html'
    initial = {}

    def get_object(self, queryset=None):
        # Retrieve object record if current user has permission to object
        return super(JobApplicationUpdateView, self).get_object()

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('career:job_application-list')

    def get_initial(self):
        initial = super(JobApplicationUpdateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial


class JobApplicationDeleteView(LoginRequiredMixin, DeleteAclMixin):
    model = models.JobApplication
    success_url = reverse_lazy('career:job-application-list')
    template_name = 'career/job_application_confirm_delete.html'
    user_field = 'applicant'
    login_url = reverse_lazy('user-login')

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(JobApplicationDeleteView, self).get_context_data(**kwargs)


class JobPostingListView(ListView):
    model = models.JobPosting
    # paginate_by = 10
    template_name = 'career/job_posting_list.html'

    def get_queryset(self):
        # Retrieve list object for the current user or approved user  
        user = self.request.user
        if user.is_authenticated:
            queryset = super(JobPostingListView, self).get_queryset()
            # filter queryset for logged in user
            queryset = queryset.filter(source=user)
            return queryset
        else:
            return super(JobPostingListView, self).get_queryset().none()


class JobPostingCreateView(LoginRequiredMixin, CreateView):
    model = models.JobPosting
    form_class = forms.JobPostingForm
    template_name = 'career/job_posting_form.html'
    initial = {}
    login_url = reverse_lazy('user-login')
    
    def form_valid(self, form):
        form.instance.source = self.request.user
        return super(JobPostingCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        initial = super(JobPostingCreateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('career:job_posting-list')


class JobPostingDetailView(DetailView):
    model = models.JobPosting
    template_name = 'career/job_posting_detail.html'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(JobPostingDetailView, self).get_context_data(**kwargs)


class JobPostingUpdateView(LoginRequiredMixin, UpdateAclMixin):
    model = models.JobPosting
    form_class = forms.JobPostingForm
    template_name = 'career/job_posting_form.html'
    initial = {}
    user_field = 'source'
    login_url = reverse_lazy('user-login')

    def get_object(self, queryset=None):
        # Retrieve object record if current user has permission to object
        return super(JobPostingUpdateView, self).get_object()

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('career:job_posting-list')

    def get_initial(self):
        initial = super(JobPostingUpdateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial


class JobPostingDeleteView(DeleteAclMixin):
    model = models.JobPosting
    success_url = reverse_lazy('career:job-posting-list')
    template_name = 'career/job_posting_confirm_delete.html'
    user_field = 'source'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(JobPostingDeleteView, self).get_context_data(**kwargs)

career/templates/career/job_application_confirm_delete.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <form method="post">{% csrf_token %}
        <h5>Delete JobApplication</h5>
        <p>Are you sure you want to delete {{ object }}?</p>
        <div class="form-group">
            <ul class="list-inline">                
                <li class="list-inline-item">
                    <a href="{% url 'career:job-application-list' %}" class="btn btn-primary">Cancel</a>
                </li>
                <li class="list-inline-item">
                    <button type="submit" class="btn btn-danger">Delete</button>            
                </li>                
            </ul>
        </div>
    </form>
    </div>
    {% endblock %}

career/templates/career/job_application_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col">
            <a class="btn btn-primary"
               href="{% url 'career:job-application-list' %}">View all
            </a>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">JobApplication Details</h5>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-3 py-3">Job Posting</dt>
                        <dd class="col-sm-9 py-3">{{ object.job_posting.title }}</dd>

                        <dt class="col-sm-3 py-3">Application Reason</dt>
                        <dd class="col-sm-9 py-3">{{ object.application_reason }}</dd>
                        <dt class="col-sm-3 py-3">Applicant</dt>
                        <dd class="col-sm-9 py-3">{{ object.applicant }}</dd>

                        <dt class="col-sm-3 py-3">Application Datetime</dt>
                        <dd class="col-sm-9 py-3">{{ object.application_datetime }}</dd>
                    </dl>
                    <section>
                        {% include 'components/entity_media_entry.html' with object=object.application_document %}
                    </section>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col p-3">
            <ul class="list-inline">
                <li class="list-inline-item">
                    <a class="btn btn-primary"
                       href="{% url 'career:job-application-update' object.slug %}">Edit
                    </a>
                </li>

                <li class="list-inline-item">
                    <a class="btn btn-primary"
                       href="{% url 'career:job-application-delete' object.slug %}">Delete
                    </a>
                </li>

            </ul>
        </div>
    </div>
</div>
{% endblock %}

career/templates/career/job_application_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'career:job-application-list' %}">Job Application Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}

career/templates/career/job_application_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if object_list %}
<div class="container my-5">
    <div class="row">
        <div class="col">
            <div class="row my-3">
                <div class="col">
                    <h5>Job Applications of {{user.public_identity}}</h5>
                </div>
            </div>
            <table class="table table-striped table-bordered table-responsive-md table-sm data-table">
                <thead class="thead-dark">
                <tr>
                    <th>Application Reason</th>
                    <th>Job Posting</th>
                    <th>Application Datetime</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                <tr>
                    <!-- Rendered content with action buttons -->
                    <td>{{object.application_reason}}</td>
                    <td>{{object.job_posting.title}}</td>
                    <td>{{object.application_datetime}}</td>
                    <td>
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <a href="{% url 'career:job-application-detail' object.slug %}" class="cmd
                cmd-detail" data-toggle="tooltip" title="View"><i class="fa fa-search-plus">&nbsp;</i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'career:job-application-update' object.slug %}" class="cmd cmd-edit"
                                   data-toggle="tooltip"
                                   title="Edit">
                                    <i class="fa fa-edit">&nbsp;</i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'career:job-application-delete' object.slug %}" class="cmd
            cmd-delete" data-toggle="tooltip" title="Delete"><i class="fa fa-trash">&nbsp;</i>
                                </a>
                            </li>
                        </ul>
                    </td>

                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-12">

            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <h5>No record exists for selected entity</h5>
                <p>You may create new record using the ADD command </p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="col">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="btn btn-primary"
                           href="{% url 'career:job-application-create' %}">Add</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn btn-primary"
                           href="{{ request.META.HTTP_REFERER }}">
                            Back
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

career/templates/career/job_posting_confirm_delete.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <form method="post">{% csrf_token %}
        <h5>Delete JobPosting</h5>
        <p>Are you sure you want to delete {{ object }}?</p>
        <div class="form-group">
            <ul class="list-inline">                
                <li class="list-inline-item">
                    <a href="{% url 'career:job-posting-list' %}" class="btn btn-primary">Cancel</a>
                </li>
                <li class="list-inline-item">
                    <button type="submit" class="btn btn-danger">Delete</button>            
                </li>                
            </ul>
        </div>
    </form>
    </div>
    {% endblock %}

career/templates/career/job_posting_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col">
            <a class="btn btn-primary"
               href="{% url 'career:job-posting-list' %}">View all
            </a>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">JobPosting Details</h5>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-3 py-3">Title</dt>
                        <dd class="col-sm-9 py-3">{{ object.title }}</dd>

                        <dt class="col-sm-3 py-3">Required Qualification Description</dt>
                        <dd class="col-sm-9 py-3">{{ object.required_qualification_description }}</dd>

                        <dt class="col-sm-3 py-3">Description</dt>
                        <dd class="col-sm-9 py-3">{{ object.description }}</dd>
                        <dt class="col-sm-3 py-3">Min Work Experience</dt>
                        <dd class="col-sm-9 py-3">{{ object.min_work_experience }}</dd>
                        <dt class="col-sm-3 py-3">Required Qualification</dt>
                        <dd class="col-sm-9 py-3">{{ object.required_qualification }}</dd>

                        <dt class="col-sm-3 py-3">Source</dt>
                        <dd class="col-sm-9 py-3">{{ object.source }}</dd>

                        <dt class="col-sm-3 py-3">Is Volunteer Job</dt>
                        <dd class="col-sm-9 py-3">{{ object.is_volunteer_job|yesno:'Yes, No' }}</dd>
                        <dt class="col-sm-3 py-3">Created At</dt>
                        <dd class="col-sm-9 py-3">{{ object.created_at }}</dd>
                        <dt class="col-sm-3 py-3">Last Modified At</dt>
                        <dd class="col-sm-9 py-3">{{ object.last_modified_at }}</dd>

                    </dl>
                    <section>
                        <dt class="col-sm-3 py-3">Approvals</dt>
                        <dd class="col-sm-9 py-3">{{ object.approvals }}</dd>
                    </section>
                    <section>
                        <dt class="col-sm-3 py-3">Application Document</dt>
                        <dd class="col-sm-9 py-3">{{ object.application_document }}</dd>
                    </section>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col p-3">
            <ul class="list-inline">
                <li class="list-inline-item">
                    <a class="btn btn-primary"
                       href="{% url 'career:job-posting-update' object.slug %}">Edit
                    </a>
                </li>

                <li class="list-inline-item">
                    <a class="btn btn-primary"
                       href="{% url 'career:job-posting-delete' object.slug %}">Delete
                    </a>
                </li>

            </ul>
        </div>
    </div>
</div>
{% endblock %}

career/templates/career/job_posting_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'career:job-posting-list' %}">Job Posting Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}

career/templates/career/job_posting_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if object_list %}
<div class="container my-5">
    <div class="row">
        <div class="col">
            <div class="row my-3">
                <div class="col">
                    <h5>Jobs posted by {{user.public_identity}}</h5>
                </div>
            </div>
            <table class="table table-striped table-bordered table-responsive-md table-sm data-table">
                <thead class="thead-dark">
                <tr>
                    <th>Title</th>
                    <th>Job Description</th>
                    <th>Qualification Description</th>
                    <th>Qualification</th>
                    <th style="width: 80px">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                <tr>
                    <!-- Rendered content with action buttons -->
                    <td>{{object.title}}</td>
                    <td>{{object.description|truncatechars:100}}</td>
                    <td>{{object.required_qualification_description|truncatechars:100}}</td>
                    <td>{{object.required_qualification}}</td>
                    <td>
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <a href="{% url 'career:job-posting-detail' object.slug %}" class="cmd
                cmd-detail" data-toggle="tooltip" title="View"><i class="fa fa-search-plus">&nbsp;</i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'career:job-posting-update' object.slug %}" class="cmd cmd-edit"
                                   data-toggle="tooltip"
                                   title="Edit">
                                    <i class="fa fa-edit">&nbsp;</i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'career:job-posting-delete' object.slug %}" class="cmd
            cmd-delete" data-toggle="tooltip" title="Delete"><i class="fa fa-trash">&nbsp;</i>
                                </a>
                            </li>
                        </ul>
                    </td>

                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-12">

            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <h5>No record exists for selected entity</h5>
                <p>You may create new record using the ADD command </p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="col">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="btn btn-primary"
                           href="{% url 'career:job-posting-create' %}">Add</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn btn-primary"
                           href="{{ request.META.HTTP_REFERER }}">
                            Back
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}