mentorship/urls.py
from django.urls import path

from mentorship import views

app_name = 'mentorship'

urlpatterns = []

urlpatterns += (
    # urls for MentoringProgramme
    path('mentoring-programme/', views.MentoringProgrammeListView.as_view(), name='mentoring-programme-list'),
    path('mentoring-programme/create/', views.MentoringProgrammeCreateView.as_view(),
         name='mentoring-programme-create'),
    path('mentoring-programme/detail/<str:slug>/', views.MentoringProgrammeDetailView.as_view(),
         name='mentoring-programme-detail'),
    path('mentoring-programme/update/<str:slug>/', views.MentoringProgrammeUpdateView.as_view(),
         name='mentoring-programme-update'),
    path('mentoring-programme/delete/<str:slug>/', views.MentoringProgrammeDeleteView.as_view(),
         name='mentoring-programme-delete')
)

urlpatterns += (
    # urls for MentoringSession
    path('mentoring-session/', views.MentoringSessionListView.as_view(), name='mentoring-session-list'),
    path('mentoring-session/create/', views.MentoringSessionCreateView.as_view(), name='mentoring-session-create'),
    path('mentoring-session/detail/<str:slug>/', views.MentoringSessionDetailView.as_view(),
         name='mentoring-session-detail'),
    path('mentoring-session/update/<str:slug>/', views.MentoringSessionUpdateView.as_view(),
         name='mentoring-session-update'),
    path('mentoring-session/delete/<str:slug>/', views.MentoringSessionDeleteView.as_view(),
         name='mentoring-session-delete')
)

tsa/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static

from tsa import settings
from achievement.urls import urlpatterns as achievement_urls
from career.urls import urlpatterns as career_urls
from mentorship.urls import urlpatterns as mentoring_urls
from profile_management.urls import urlpatterns as profile_management_urls
from social_network.urls import urlpatterns as social_urls
from util.registration import urlpatterns as registration_urls
from util.site import urlpatterns as site_urls
from util.urls import urlpatterns as util_urls
from volunteer.urls import urlpatterns as volunteer_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(site_urls + registration_urls)),
    path('mentorship/', include((mentoring_urls, 'mentorship'))),
    path('util/', include((util_urls, 'util'))),
    path('achievement/', include((achievement_urls, 'achievement'))),
    path('career/', include((career_urls, 'career'))),
    path('profile_management/', include((profile_management_urls, 'profile_management'))),
    path('social_network/', include((social_urls, 'social_network'))),
    path('volunteer/', include((volunteer_urls, 'volunteer'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentorship/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models

from util.models import BaseModel, name_default, text_default, code_default, BaseUser, datetime_default, PublishMixin, \
    FileUploadMixin


class BaseEvent(BaseModel):
    event_name = models.CharField(**name_default)
    event_comment = models.TextField(**text_default)
    event_start = models.DateTimeField(**datetime_default)
    event_end = models.DateTimeField(null=True)
    event_type = models.CharField(null=True, **code_default)

    class Meta:
        abstract = True


class MentoringProgramme(FileUploadMixin, PublishMixin, BaseModel):
    programme_name = models.CharField(**name_default)
    programme_start = models.DateTimeField(**datetime_default)
    programme_end = models.DateTimeField(**datetime_default)

    source = models.ForeignKey('util.BaseUser', related_name='mentoring_programme', on_delete=models.DO_NOTHING)
    approvals = GenericRelation('util.Approval', related_name='mentoring_programmes')
    objectives = models.TextField(**text_default)

    def publish(self, **kwargs):
        self.broadcasts = '__all__'


class MentoringSession(FileUploadMixin, PublishMixin, BaseEvent):
    programme = models.ForeignKey(MentoringProgramme, on_delete=models.CASCADE, related_name='mentoring_session')
    mentor = models.ForeignKey(BaseUser, related_name="mentor", on_delete=models.DO_NOTHING)
    pupil = models.ForeignKey(BaseUser, related_name="pupil", on_delete=models.DO_NOTHING)

    def publish(self, **kwargs):
        self.broadcast_order = ['mentoring_session', 'mentor', 'pupil']
        return super(MentoringSession, self).publish(**kwargs)

mentorship/forms.py
from django import forms
from mentorship import models


class MentoringProgrammeForm(forms.ModelForm):

    def get_initial_for_field(self, field, field_name):
        # override the initial value for the specified form field
        return super(MentoringProgrammeForm, self).get_initial_for_field(field, field_name)

    class Meta:
        model = models.MentoringProgramme
        fields = '__all__'
        exclude = ['source', 'approvals']


class MentoringSessionForm(forms.ModelForm):

    def get_initial_for_field(self, field, field_name):
        # override the initial value for the specified form field
        return super(MentoringSessionForm, self).get_initial_for_field(field, field_name)

    class Meta:
        model = models.MentoringSession
        fields = '__all__'      

mentorship/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView

from mentorship import forms
from mentorship import models
from util.views import DeleteAclMixin, UpdateAclMixin, ReadOnlyMixin


class MentoringProgrammeListView(ListView):
    model = models.MentoringProgramme
    # paginate_by = 10
    template_name = 'mentorship/mentoring_programme_list.html'

    def get_queryset(self):
        # Retrieve list object for the current user or approved user  
        user = self.request.user
        if user.is_authenticated:
            queryset = super(MentoringProgrammeListView, self).get_queryset()
            # filter queryset for logged in user
            # @todo: customise approval to show only entries with status == APPROVED
            queryset = queryset.all()
            return queryset
        else:
            return super(MentoringProgrammeListView, self).get_queryset().none()


class MentoringProgrammeCreateView(LoginRequiredMixin, CreateView):
    model = models.MentoringProgramme
    form_class = forms.MentoringProgrammeForm
    template_name = 'mentorship/mentoring_programme_form.html'
    initial = {}
    login_url = reverse_lazy('user-login')
    
    def form_valid(self, form):
        form.instance.source = self.request.user
        return super(MentoringProgrammeCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        initial = super(MentoringProgrammeCreateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('mentorship:mentoring_programme-list')


class MentoringProgrammeDetailView(DetailView):
    model = models.MentoringProgramme
    template_name = 'mentorship/mentoring_programme_detail.html'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(MentoringProgrammeDetailView, self).get_context_data(**kwargs)


class MentoringProgrammeUpdateView(UpdateAclMixin):
    model = models.MentoringProgramme
    form_class = forms.MentoringProgrammeForm
    template_name = 'mentorship/mentoring_programme_form.html'
    initial = {}
    user_field = 'source'

    def get_object(self, queryset=None):
        # Retrieve object record if current user has permission to object
        return super(MentoringProgrammeUpdateView, self).get_object()

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('mentorship:mentoring_programme-list')

    def get_initial(self):
        initial = super(MentoringProgrammeUpdateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial


class MentoringProgrammeDeleteView(DeleteAclMixin):
    model = models.MentoringProgramme
    success_url = reverse_lazy('mentorship:mentoring-programme-list')
    template_name = 'mentorship/mentoring_programme_confirm_delete.html'
    user_field = 'source'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(MentoringProgrammeDeleteView, self).get_context_data(**kwargs)


class MentoringSessionListView(LoginRequiredMixin, ListView):
    model = models.MentoringSession
    # paginate_by = 10
    template_name = 'mentorship/mentoring_session_list.html'
    login_url = reverse_lazy('user-login')

    def get_queryset(self):
        # Retrieve list object for the current user or approved user  
        user = self.request.user
        if user.is_authenticated:
            queryset = super(MentoringSessionListView, self).get_queryset()
            # filter queryset for logged in user
            queryset = queryset.filter(Q(mentor=user) | Q(pupil=user))
            return queryset
        else:
            return super(MentoringSessionListView, self).get_queryset().none()


class MentoringSessionCreateView(LoginRequiredMixin, CreateView):
    model = models.MentoringSession
    form_class = forms.MentoringSessionForm
    template_name = 'mentorship/mentoring_session_form.html'
    initial = {}

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        initial = super(MentoringSessionCreateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('mentorship:mentoring_session-list')


class MentoringSessionDetailView(LoginRequiredMixin, DetailView):
    model = models.MentoringSession
    template_name = 'mentorship/mentoring_session_detail.html'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(MentoringSessionDetailView, self).get_context_data(**kwargs)


class MentoringSessionUpdateView(ReadOnlyMixin):
    model = models.MentoringSession
    form_class = forms.MentoringSessionForm
    template_name = 'mentorship/mentoring_session_form.html'
    initial = {}


class MentoringSessionDeleteView(ReadOnlyMixin):
    model = models.MentoringSession
    success_url = reverse_lazy('mentorship:mentoring-session-list')
    template_name = 'mentorship/mentoring_session_confirm_delete.html'

mentorship/templates/mentorship/mentoring_programme_confirm_delete.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <form method="post">{% csrf_token %}
        <h5>Delete MentoringProgramme</h5>
        <p>Are you sure you want to delete {{ object }}?</p>
        <div class="form-group">
            <ul class="list-inline">                
                <li class="list-item">
                    <button href="{% url 'mentorship:mentoring-programme-list' %}" class="btn btn-primary">Cancel</button>
                </li>
                <li class="list-item">
                    <button type="submit" class="btn btn-danger">Delete</button>            
                </li>                
            </ul>
        </div>
    </form>
    </div>
    {% endblock %}

mentorship/templates/mentorship/mentoring_programme_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col">
            <a class="btn btn-primary"
               href="{% url 'mentorship:mentoring-programme-list' %}">View all
            </a>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Mentoring Programme Details</h5>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-3 py-3">Programme Name</dt>
                        <dd class="col-sm-9 py-3">{{ object.programme_name }}</dd>
                        <dt class="col-sm-3 py-3">Programme Start</dt>
                        <dd class="col-sm-9 py-3">{{ object.programme_start }}</dd>
                        <dt class="col-sm-3 py-3">Programme End</dt>
                        <dd class="col-sm-9 py-3">{{ object.programme_end }}</dd>
                        <dt class="col-sm-3 py-3">Objectives</dt>
                        <dd class="col-sm-9 py-3">{{ object.objectives }}</dd>
                    </dl>
                    <section>
                        {% include 'components/entity_media_entry.html' with object=object.media %}
                    </section>
                    <section>

                        {% if object.mentoring_session.all %}
                        <h6 class="card card-header">Mentoring Sessions</h6>
                        <div class="container my-3">
                            <div class="row">
                                <div class="col-12">
                                    <ul class="list-unstyled ">
                                        {% for m_session in object.mentoring_session.all %}
                                        <li class="list-item my-3">
                                            <div class="card entry-card">
                                                <div class="card-body">{{m_session.event_comment}}</div>
                                                <div class="card-footer entry-card-footer">
                                                    <ul class="list-inline">
                                                        <li class="list-inline-item"><strong>Title</strong>&nbsp;
                                                            {{m_session.event_name}}
                                                        </li>
                                                        <li class="list-inline-item"><strong>Event date &
                                                            time</strong>&nbsp;
                                                            {{m_session.event_start}}
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </section>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col p-3">
            <ul class="list-inline">
                <li class="list-inline-item">
                    <a class="btn btn-primary"
                       href="{% url 'mentorship:mentoring-programme-update' object.slug %}">Edit
                    </a>
                </li>

                <li class="list-inline-item">
                    <a class="btn btn-primary"
                       href="{% url 'mentorship:mentoring-programme-delete' object.slug %}">Delete
                    </a>
                </li>

            </ul>
        </div>
    </div>
</div>
{% endblock %}

mentorship/templates/mentorship/mentoring_programme_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'mentorship:mentoring-programme-list' %}">Mentoring Programme Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}

mentorship/templates/mentorship/mentoring_programme_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if object_list %}
<div class="container my-5">
    <div class="row">
        <div class="col">
            <div class="row my-3">
                <div class="col">
                    <h5>Mentoring programmes by {{user.public_identity}}</h5>
                </div>
            </div>
            <table class="table table-striped table-bordered table-responsive-md table-sm data-table">
                <thead class="thead-dark">
                <tr>
                    <th>Media</th>
                    <th>Programme Name</th>
                    <th>Programme Start</th>
                    <th>Programme End</th>
                    <th style="width: 20%">Objectives</th>
                    <th style="width: 80px">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                <tr>
                    <!-- Rendered content with action buttons -->
                    <td>{{object.media}}</td>
                    <td>{{object.programme_name}}</td>
                    <td>{{object.programme_start}}</td>
                    <td>{{object.programme_end}}</td>
                    <td>{{object.objectives}}</td>
                    <td>
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <a href="{% url 'mentorship:mentoring-programme-detail' object.slug %}" class="cmd
                cmd-detail" data-toggle="tooltip" title="View"><i class="fa fa-search-plus">&nbsp;</i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'mentorship:mentoring-programme-update' object.slug %}"
                                   class="cmd cmd-edit" data-toggle="tooltip"
                                   title="Edit">
                                    <i class="fa fa-edit">&nbsp;</i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'mentorship:mentoring-programme-delete' object.slug %}" class="cmd
            cmd-delete" data-toggle="tooltip" title="Delete"><i class="fa fa-trash">&nbsp;</i>
                                </a>
                            </li>
                        </ul>
                    </td>

                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-12">

            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <h5>No record exists for selected entity</h5>
                <p>You may create new record using the ADD command </p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="col">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="btn btn-primary"
                           href="{% url 'mentorship:mentoring-programme-create' %}">Add</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn btn-primary"
                           href="{{ request.META.HTTP_REFERER }}">
                            Back
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

mentorship/templates/mentorship/mentoring_session_confirm_delete.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <form method="post">{% csrf_token %}
        <h5>Delete MentoringSession</h5>
        <p>Are you sure you want to delete {{ object }}?</p>
        <div class="form-group">
            <ul class="list-inline">                
                <li class="list-item">
                    <button href="{% url 'mentorship:mentoring-session-list' %}" class="btn btn-primary">Cancel</button>
                </li>
                <li class="list-item">
                    <button type="submit" class="btn btn-danger">Delete</button>            
                </li>                
            </ul>
        </div>
    </form>
    </div>
    {% endblock %}

mentorship/templates/mentorship/mentoring_session_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <div class="container my-5">
        <div class="row">
            <div class="col">
                <a class="btn btn-primary"
                   href="{% url 'mentorship:mentoring-session-list' %}">View All MentoringSession
                </a>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">MentoringSession Details</h5>
                    </div>
                    <div class="card-body">
                        <dl class="row"><dt class="col-sm-3 py-3">Coverage</dt><dd class="col-sm-9 py-3">{{ object.coverage }}</dd><dt class="col-sm-3 py-3">Event Name</dt><dd class="col-sm-9 py-3">{{ object.event_name }}</dd><dt class="col-sm-3 py-3">Programme</dt><dd class="col-sm-9 py-3">{{ object.programme }}</dd><dt class="col-sm-3 py-3">Mentor</dt><dd class="col-sm-9 py-3">{{ object.mentor }}</dd><dt class="col-sm-3 py-3">Event Start</dt><dd class="col-sm-9 py-3">{{ object.event_start }}</dd><dt class="col-sm-3 py-3">Event End</dt><dd class="col-sm-9 py-3">{{ object.event_end }}</dd><dt class="col-sm-3 py-3">Event Type</dt><dd class="col-sm-9 py-3">{{ object.event_type }}</dd><dt class="col-sm-3 py-3">Event Comment</dt><dd class="col-sm-9 py-3">{{ object.event_comment }}</dd><dt class="col-sm-3 py-3">Pupil</dt><dd class="col-sm-9 py-3">{{ object.pupil }}</dd></dl>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row mt-4">
            <div class="col p-3">
            <ul class="list-inline">
            <li class="list-inline-item">
                <a class="btn btn-primary" 
                    href="{% url 'mentorship:mentoring-session-update' object.slug %}">Edit
                </a>
            </li>
    
            <li class="list-inline-item">
                <a class="btn btn-primary"
                   href="{% url 'mentorship:mentoring-session-delete' object.slug %}">Delete
                </a>
            </li>
    
            </ul>            
            </div>
        </div>
    </div>
    {% endblock %}

mentorship/templates/mentorship/mentoring_session_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'mentorship:mentoring-session-list' %}">Mentoring Session Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}

mentorship/templates/mentorship/mentoring_session_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if object_list %}
<div class="container my-5">
    <div class="row">
        <div class="col">
            <div class="row my-3">
                <div class="col">
                    <h5>Mentoring session for {{user.public_identity}}</h5>
                </div>
            </div>
            <table class="table table-striped table-bordered table-responsive table-sm data-table">
                <thead class="thead-dark">
                <tr>
                    <th>Event Name</th>
                    <th>Programme</th>
                    <th>Mentor</th>
                    <th>Pupil</th>
                    <th>Event Start</th>
                    <th>Event End</th>
                    <th>Event Type</th>
                    <th>Event Comment</th>

                    <th style="width: 80px">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                <tr>
                    <!-- Rendered content with action buttons -->
                    <td>{{object.event_name}}</td>
                    <td>
                        <a href="{% url 'mentorship:mentoring-programme-detail' object.programme.slug %}">
                            {{object.programme.programme_name}}</a>
                    </td>
                    <td>{{object.mentor}}</td>
                    <td>{{object.pupil}}</td>
                    <td>{{object.event_start}}</td>
                    <td>{{object.event_end}}</td>
                    <td>{{object.event_type}}</td>
                    <td>{{object.event_comment}}</td>

                    <td>
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <a href="{% url 'mentorship:mentoring-session-detail' object.slug %}" class="cmd
                cmd-detail" data-toggle="tooltip" title="View"><i class="fa fa-search-plus">&nbsp;</i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'mentorship:mentoring-session-update' object.slug %}"
                                   class="cmd cmd-edit" data-toggle="tooltip"
                                   title="Edit">
                                    <i class="fa fa-edit">&nbsp;</i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'mentorship:mentoring-session-delete' object.slug %}" class="cmd
            cmd-delete" data-toggle="tooltip" title="Delete"><i class="fa fa-trash">&nbsp;</i>
                                </a>
                            </li>
                        </ul>
                    </td>

                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-12">

            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <h5>No record exists for selected entity</h5>
                <p>You may create new record using the ADD command </p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="col">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="btn btn-primary"
                           href="{% url 'mentorship:mentoring-session-create' %}">Add</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn btn-primary"
                           href="{{ request.META.HTTP_REFERER }}">
                            Back
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}