tsa/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static

from tsa import settings
from achievement.urls import urlpatterns as achievement_urls
from career.urls import urlpatterns as career_urls
from mentorship.urls import urlpatterns as mentoring_urls
from profile_management.urls import urlpatterns as profile_management_urls
from social_network.urls import urlpatterns as social_urls
from util.registration import urlpatterns as registration_urls
from util.site import urlpatterns as site_urls
from util.urls import urlpatterns as util_urls
from volunteer.urls import urlpatterns as volunteer_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(site_urls + registration_urls)),
    path('mentorship/', include((mentoring_urls, 'mentorship'))),
    path('util/', include((util_urls, 'util'))),
    path('achievement/', include((achievement_urls, 'achievement'))),
    path('career/', include((career_urls, 'career'))),
    path('profile_management/', include((profile_management_urls, 'profile_management'))),
    path('social_network/', include((social_urls, 'social_network'))),
    path('volunteer/', include((volunteer_urls, 'volunteer'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

util/urls.py
from django.urls import path

from util import views

app_name = 'util'

urlpatterns = []

urlpatterns += (
    # urls for Address
    path('address/', views.AddressListView.as_view(), name='address-list'),
    path('address/create/', views.AddressCreateView.as_view(), name='address-create'),
    path('address/detail/<str:slug>/', views.AddressDetailView.as_view(), name='address-detail'),
    path('address/update/<str:slug>/', views.AddressUpdateView.as_view(), name='address-update'),
    path('address/delete/<str:slug>/', views.AddressDeleteView.as_view(), name='address-delete')
)

urlpatterns += (
    # urls for Approval
    path('approval/', views.ApprovalListView.as_view(), name='approval-list'),
    path('approval/create/', views.ApprovalCreateView.as_view(), name='approval-create'),
    path('approval/detail/<str:slug>/', views.ApprovalDetailView.as_view(), name='approval-detail'),
    path('approval/update/<str:slug>/', views.ApprovalUpdateView.as_view(), name='approval-update'),
    path('approval/delete/<str:slug>/', views.ApprovalDeleteView.as_view(), name='approval-delete')
)

urlpatterns += (
    # urls for Institution
    path('institution/', views.InstitutionListView.as_view(), name='institution-list'),
    path('institution/create/', views.InstitutionCreateView.as_view(), name='institution-create'),
    path('institution/detail/<str:slug>/', views.InstitutionDetailView.as_view(), name='institution-detail'),
    path('institution/update/<str:slug>/', views.InstitutionUpdateView.as_view(), name='institution-update'),
    path('institution/delete/<str:slug>/', views.InstitutionDeleteView.as_view(), name='institution-delete')
)

urlpatterns += (
    # urls for Notification
    path('notification/', views.NotificationListView.as_view(), name='notification-list'),
    path('notification/create/', views.NotificationCreateView.as_view(), name='notification-create'),
    path('notification/detail/<str:slug>/', views.NotificationDetailView.as_view(), name='notification-detail'),
    path('notification/update/<str:slug>/', views.NotificationUpdateView.as_view(), name='notification-update'),
    path('notification/delete/<str:slug>/', views.NotificationDeleteView.as_view(), name='notification-delete')
)

urlpatterns += (
    # urls for NotificationResponse
    path('notification-response/', views.NotificationResponseListView.as_view(), name='notification-response-list'),
    path('notification-response/create/', views.NotificationResponseCreateView.as_view(),
         name='notification-response-create'),
    path('notification-response/detail/<str:slug>/', views.NotificationResponseDetailView.as_view(),
         name='notification-response-detail'),
    path('notification-response/update/<str:slug>/', views.NotificationResponseUpdateView.as_view(),
         name='notification-response-update'),
    path('notification-response/delete/<str:slug>/', views.NotificationResponseDeleteView.as_view(),
         name='notification-response-delete')
)

urlpatterns += (
    # urls for Signature
    path('signature/', views.SignatureListView.as_view(), name='signature-list'),
    path('signature/create/', views.SignatureCreateView.as_view(), name='signature-create'),
    path('signature/detail/<str:slug>/', views.SignatureDetailView.as_view(), name='signature-detail'),
    path('signature/update/<str:slug>/', views.SignatureUpdateView.as_view(), name='signature-update'),
    path('signature/delete/<str:slug>/', views.SignatureDeleteView.as_view(), name='signature-delete')
)

urlpatterns += (
    # urls for UserAvatar
    path('user-avatar/', views.UserAvatarListView.as_view(), name='user-avatar-list'),
    path('user-avatar/create/', views.UserAvatarCreateView.as_view(), name='user-avatar-create'),
    path('user-avatar/detail/<str:slug>/', views.UserAvatarDetailView.as_view(), name='user-avatar-detail'),
    path('user-avatar/update/<str:slug>/', views.UserAvatarUpdateView.as_view(), name='user-avatar-update'),
    path('user-avatar/delete/<str:slug>/', views.UserAvatarDeleteView.as_view(), name='user-avatar-delete')
)

urlpatterns += (
    # urls for UserPreferences
    path('user-preferences/', views.UserPreferencesListView.as_view(), name='user-preferences-list'),
    path('user-preferences/create/', views.UserPreferencesCreateView.as_view(), name='user-preferences-create'),
    path('user-preferences/detail/<str:slug>/', views.UserPreferencesDetailView.as_view(),
         name='user-preferences-detail'),
    path('user-preferences/update/<str:slug>/', views.UserPreferencesUpdateView.as_view(),
         name='user-preferences-update'),
    path('user-preferences/delete/<str:slug>/', views.UserPreferencesDeleteView.as_view(),
         name='user-preferences-delete')
)

urlpatterns += (
    # urls for UserSignedDocument
    path('user-signed-document/', views.UserSignedDocumentListView.as_view(), name='user-signed-document-list'),
    path('user-signed-document/create/', views.UserSignedDocumentCreateView.as_view(),
         name='user-signed-document-create'),
    path('user-signed-document/detail/<str:slug>/', views.UserSignedDocumentDetailView.as_view(),
         name='user-signed-document-detail'),
    path('user-signed-document/update/<str:slug>/', views.UserSignedDocumentUpdateView.as_view(),
         name='user-signed-document-update'),
    path('user-signed-document/delete/<str:slug>/', views.UserSignedDocumentDeleteView.as_view(),
         name='user-signed-document-delete')
)

urlpatterns += (
    # urls for UserUploadedDocument
    path('user-uploaded-document/', views.UserUploadedDocumentListView.as_view(), name='user-uploaded-document-list'),
    path('user-uploaded-document/create/', views.UserUploadedDocumentCreateView.as_view(),
         name='user-uploaded-document-create'),
    path('user-uploaded-document/detail/<str:slug>/', views.UserUploadedDocumentDetailView.as_view(),
         name='user-uploaded-document-detail'),
    path('user-uploaded-document/update/<str:slug>/', views.UserUploadedDocumentUpdateView.as_view(),
         name='user-uploaded-document-update'),
    path('user-uploaded-document/delete/<str:slug>/', views.UserUploadedDocumentDeleteView.as_view(),
         name='user-uploaded-document-delete')
)

util/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView, UpdateView, CreateView, RedirectView, TemplateView

from util import forms
from util import models


class DeleteAclMixin(DeleteView):
    user_field = None
    access_redirect = reverse_lazy('access-denied')

    def get_object(self, queryset=None):
        if self.request.user.is_authenticated:
            slug = self.kwargs.get(self.slug_url_kwarg)
            pk = self.kwargs.get(self.pk_url_kwarg)
            if pk is not None:
                queryset = queryset.filter(**{'pk': pk, f'{self.user_field}': self.request.user})
            if slug is not None and (pk is None or self.query_pk_and_slug):
                queryset = self.model.objects.filter(**{f'{self.user_field}': self.request.user, f'{self.slug_field}':
                    slug})
            try:
                return queryset.get()
            except ObjectDoesNotExist:
                return None

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.object:
            return HttpResponseRedirect(self.access_redirect)
        else:
            return super(DeleteAclMixin, self).get(request, *args, **kwargs)


class UpdateAclMixin(UpdateView):
    user_field = None
    access_redirect = reverse_lazy('access-denied')

    def get_object(self, queryset=None):
        if self.request.user.is_authenticated:
            slug = self.kwargs.get(self.slug_url_kwarg)
            pk = self.kwargs.get(self.pk_url_kwarg)
            if pk is not None:
                queryset = queryset.filter(**{'pk': pk, f'{self.user_field}': self.request.user})
            if slug is not None and (pk is None or self.query_pk_and_slug):
                queryset = self.model.objects.filter(**{f'{self.user_field}': self.request.user, f'{self.slug_field}':
                    slug})
            try:
                return queryset.get()
            except ObjectDoesNotExist:
                return None

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.object:
            return HttpResponseRedirect(self.access_redirect)
        else:
            return super(UpdateAclMixin, self).get(request, *args, **kwargs)


class AccessRedirectView(TemplateView):
    template_name = 'access_denied_redirect.html'


class ReadOnlyMixin(RedirectView):

    def __init__(self, *args, **kwargs):
        if not self.url:
            self.url = reverse_lazy(self.request.META.get('HTTP_REFERER'))
        super(ReadOnlyMixin, self).__init__(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        return HttpResponseRedirect(self.url)

    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(self.url)


class AddressListView(ListView):
    model = models.Address
    # paginate_by = 10
    template_name = 'util/address_list.html'

    def get_queryset(self):
        # Retrieve list object for the current user or approved user  
        user = self.request.user
        if user.is_authenticated:
            queryset = super(AddressListView, self).get_queryset()
            # filter queryset for logged in user
            return queryset
        else:
            return super(AddressListView, self).get_queryset().none()


class AddressCreateView(CreateView):
    model = models.Address
    form_class = forms.AddressForm
    template_name = 'util/address_form.html'
    initial = {}

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        initial = super(AddressCreateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('util:address-list')


class AddressDetailView(DetailView):
    model = models.Address
    template_name = 'util/address_detail.html'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(AddressDetailView, self).get_context_data(**kwargs)


class AddressUpdateView(ReadOnlyMixin):
    model = models.Address
    form_class = forms.AddressForm
    template_name = 'util/address_form.html'
    initial = {}


class AddressDeleteView(ReadOnlyMixin):
    model = models.Address
    success_url = reverse_lazy('util:address-list')
    template_name = 'util/address_confirm_delete.html'


class ApprovalListView(ListView):
    model = models.Approval
    # paginate_by = 10
    template_name = 'util/approval_list.html'

    def get_queryset(self):
        # Retrieve list object for the current user or approved user  
        user = self.request.user
        if user.is_authenticated:
            queryset = super(ApprovalListView, self).get_queryset()
            # filter queryset for logged in user
            return queryset
        else:
            return super(ApprovalListView, self).get_queryset().none()


class ApprovalCreateView(CreateView):
    model = models.Approval
    form_class = forms.ApprovalForm
    template_name = 'util/approval_form.html'
    initial = {}

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        initial = super(ApprovalCreateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('util:approval-list')


class ApprovalDetailView(DetailView):
    model = models.Approval
    template_name = 'util/approval_detail.html'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(ApprovalDetailView, self).get_context_data(**kwargs)


class ApprovalUpdateView(ReadOnlyMixin):
    model = models.Approval
    form_class = forms.ApprovalForm
    template_name = 'util/approval_form.html'
    initial = {}


class ApprovalDeleteView(ReadOnlyMixin):
    model = models.Approval
    success_url = reverse_lazy('util:approval-list')
    template_name = 'util/approval_confirm_delete.html'


class InstitutionListView(ListView):
    model = models.Institution
    # paginate_by = 10
    template_name = 'util/institution_list.html'

    def get_queryset(self):
        # Retrieve list object for the current user or approved user  
        user = self.request.user
        if user.is_authenticated:
            queryset = super(InstitutionListView, self).get_queryset()
            # filter queryset for logged in user
            return queryset
        else:
            return super(InstitutionListView, self).get_queryset().none()


class InstitutionCreateView(CreateView):
    model = models.Institution
    form_class = forms.InstitutionForm
    template_name = 'util/institution_form.html'
    initial = {}

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        initial = super(InstitutionCreateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('util:institution-list')


class InstitutionDetailView(DetailView):
    model = models.Institution
    template_name = 'util/institution_detail.html'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(InstitutionDetailView, self).get_context_data(**kwargs)


class InstitutionUpdateView(ReadOnlyMixin):
    model = models.Institution
    form_class = forms.InstitutionForm
    template_name = 'util/institution_form.html'
    initial = {}


class InstitutionDeleteView(ReadOnlyMixin):
    model = models.Institution
    success_url = reverse_lazy('util:institution-list')
    template_name = 'util/institution_confirm_delete.html'


class NotificationListView(ListView):
    model = models.Notification
    # paginate_by = 10
    template_name = 'util/notification_list.html'

    def get_queryset(self):
        # Retrieve list object for the current user or approved user  
        user = self.request.user
        if user.is_authenticated:
            queryset = super(NotificationListView, self).get_queryset()
            # filter queryset for logged in user
            return queryset
        else:
            return super(NotificationListView, self).get_queryset().none()


class NotificationCreateView(CreateView):
    model = models.Notification
    form_class = forms.NotificationForm
    template_name = 'util/notification_form.html'
    initial = {}

    def post(self, request, *args, **kwargs):
        form = self.get_form()

util/templates/util/institution_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <div class="container my-5">
        <div class="row">
            <div class="col">
                <a class="btn btn-primary"
                   href="{% url 'util:institution-list' %}">View All Institution
                </a>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Institution Details</h5>
                    </div>
                    <div class="card-body">
                        <dl class="row"><dt class="col-sm-3 py-3">Contact</dt><dd class="col-sm-9 py-3">{{ object.contact }}</dd><dt class="col-sm-3 py-3">Educationhistory</dt><dd class="col-sm-9 py-3">{{ object.educationhistory }}</dd><dt class="col-sm-3 py-3">Addresses</dt><dd class="col-sm-9 py-3">{{ object.addresses }}</dd><dt class="col-sm-3 py-3">Institution Name</dt><dd class="col-sm-9 py-3">{{ object.institution_name }}</dd><dt class="col-sm-3 py-3">Is Academic</dt><dd class="col-sm-9 py-3">{{ object.is_academic }}</dd><dt class="col-sm-3 py-3">Qualification</dt><dd class="col-sm-9 py-3">{{ object.qualification }}</dd></dl>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row mt-4">
            <div class="col p-3">
            <ul class="list-inline">
            <li class="list-inline-item">
                <a class="btn btn-primary" 
                    href="{% url 'util:institution-update' object.slug %}">Edit
                </a>
            </li>
    
            <li class="list-inline-item">
                <a class="btn btn-primary"
                   href="{% url 'util:institution-delete' object.slug %}">Delete
                </a>
            </li>
    
            </ul>            
            </div>
        </div>
    </div>
    {% endblock %}

util/templates/util/notification_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <div class="container my-5">
        <div class="row">
            <div class="col">
                <a class="btn btn-primary"
                   href="{% url 'util:notification-list' %}">View All Notification
                </a>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Notification Details</h5>
                    </div>
                    <div class="card-body">
                        <dl class="row"><dt class="col-sm-3 py-3">Created At</dt><dd class="col-sm-9 py-3">{{ object.created_at }}</dd><dt class="col-sm-3 py-3">Notification Code</dt><dd class="col-sm-9 py-3">{{ object.notification_code }}</dd><dt class="col-sm-3 py-3">Notificationresponse</dt><dd class="col-sm-9 py-3">{{ object.notificationresponse }}</dd><dt class="col-sm-3 py-3">Header</dt><dd class="col-sm-9 py-3">{{ object.header }}</dd><dt class="col-sm-3 py-3">Message</dt><dd class="col-sm-9 py-3">{{ object.message }}</dd><dt class="col-sm-3 py-3">Recipients</dt><dd class="col-sm-9 py-3">{{ object.recipients }}</dd><dt class="col-sm-3 py-3">Last Modified At</dt><dd class="col-sm-9 py-3">{{ object.last_modified_at }}</dd><dt class="col-sm-3 py-3">Notification Reason</dt><dd class="col-sm-9 py-3">{{ object.notification_reason }}</dd></dl>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row mt-4">
            <div class="col p-3">
            <ul class="list-inline">
            <li class="list-inline-item">
                <a class="btn btn-primary" 
                    href="{% url 'util:notification-update' object.slug %}">Edit
                </a>
            </li>
    
            <li class="list-inline-item">
                <a class="btn btn-primary"
                   href="{% url 'util:notification-delete' object.slug %}">Delete
                </a>
            </li>
    
            </ul>            
            </div>
        </div>
    </div>
    {% endblock %}

util/templates/util/notification_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'util:notification-list' %}">Notification Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}

util/templates/util/notification_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if object_list %}
    <div class="container my-5">
    <div class="row">
        <div class="col">    
            <table class="table table-striped table-bordered table-responsive table-sm data-table">
                <thead class="thead-dark">
                <tr><th>Created At</th><th>Notification Code</th><th>Notificationresponse</th><th>Header</th><th>Message</th><th>Recipients</th><th>Last Modified At</th><th>Notification Reason</th><th>Actions</th></tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <!-- Rendered content with action buttons -->
                        <td>{{object.created_at}}</td><td>{{object.notification_code}}</td><td>{{object.notificationresponse}}</td><td>{{object.header}}</td><td>{{object.message}}</td><td>{{object.recipients}}</td><td>{{object.last_modified_at}}</td><td>{{object.notification_reason}}</td>
<td>
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="{% url 'util:notification-detail' object.slug %}" class="cmd 
                cmd-detail" data-toggle="tooltip" title="View"><i class="fa fa-search-plus">&nbsp;</i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{% url 'util:notification-update' object.slug %}" class="cmd cmd-edit" data-toggle="tooltip" 
title="Edit">
                <i class="fa fa-edit">&nbsp;</i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{% url 'util:notification-delete' object.slug %}" class="cmd 
            cmd-delete" data-toggle="tooltip" title="Delete"><i class="fa fa-trash">&nbsp;</i>
            </a>
        </li>
    </ul>
</td>
                        
                    </tr>
                {% endfor %}        
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-12">

            <div class="alert alert-info alert-dismissible fade show" role="alert">
               <h5>No record exists for selected entity</h5>
              <p>You may create new record using the ADD command </p>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="col">                    
               <ul class="list-inline">
                  <li class="list-inline-item">
                    <a class="btn btn-primary" 
                    href="{% url 'util:notification-create' %}" >Add</a>
                  </li>
                  <li class="list-inline-item">
                    <a class="btn btn-primary" 
                        href="{{ request.META.HTTP_REFERER }}">
                        Back
                    </a>
                  </li>                      
                </ul>                    
            </div>          
        </div>        
    </div>
    </div>
    {% endif %}
    {% endblock %}

util/templates/util/notification_response_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'util:notification-response-list' %}">Notification Response Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}

util/templates/util/signature_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <div class="container my-5">
        <div class="row">
            <div class="col">
                <a class="btn btn-primary"
                   href="{% url 'util:signature-list' %}">View All Signature
                </a>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Signature Details</h5>
                    </div>
                    <div class="card-body">
                        <dl class="row"><dt class="col-sm-3 py-3">Created At</dt><dd class="col-sm-9 py-3">{{ object.created_at }}</dd><dt class="col-sm-3 py-3">Last Modified At</dt><dd class="col-sm-9 py-3">{{ object.last_modified_at }}</dd><dt class="col-sm-3 py-3">Signature Hash</dt><dd class="col-sm-9 py-3">{{ object.signature_hash }}</dd><dt class="col-sm-3 py-3">Signature Timestamp</dt><dd class="col-sm-9 py-3">{{ object.signature_timestamp }}</dd><dt class="col-sm-3 py-3">Signature Image</dt><dd class="col-sm-9 py-3">{{ object.signature_image }}</dd><dt class="col-sm-3 py-3">Usersigneddocument</dt><dd class="col-sm-9 py-3">{{ object.usersigneddocument }}</dd><dt class="col-sm-3 py-3">Signature 2fa</dt><dd class="col-sm-9 py-3">{{ object.signature_2fa }}</dd></dl>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row mt-4">
            <div class="col p-3">
            <ul class="list-inline">
            <li class="list-inline-item">
                <a class="btn btn-primary" 
                    href="{% url 'util:signature-update' object.slug %}">Edit
                </a>
            </li>
    
            <li class="list-inline-item">
                <a class="btn btn-primary"
                   href="{% url 'util:signature-delete' object.slug %}">Delete
                </a>
            </li>
    
            </ul>            
            </div>
        </div>
    </div>
    {% endblock %}

util/templates/util/signature_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'util:signature-list' %}">Signature Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}

util/templates/util/user_address_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'util:user-address-list' %}">User Address Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}

util/templates/util/user_avatar_confirm_delete.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <form method="post">{% csrf_token %}
        <h5>Delete UserAvatar</h5>
        <p>Are you sure you want to delete {{ object }}?</p>
        <div class="form-group">
            <ul class="list-inline">                
                <li class="list-inline-item">
                    <a href="{% url 'util:user-avatar-list' %}" class="btn btn-primary">Cancel</a>
                </li>
                <li class="list-inline-item">
                    <button type="submit" class="btn btn-danger">Delete</button>            
                </li>                
            </ul>
        </div>
    </form>
    </div>
    {% endblock %}

util/templates/util/user_preferences_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'util:user-preferences-list' %}">User Preferences Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}

util/templates/util/user_signed_document_confirm_delete.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <form method="post">{% csrf_token %}
        <h5>Delete UserSignedDocument</h5>
        <p>Are you sure you want to delete {{ object }}?</p>
        <div class="form-group">
            <ul class="list-inline">                
                <li class="list-inline-item">
                    <a href="{% url 'util:user-signed-document-list' %}" class="btn btn-primary">Cancel</a>
                </li>
                <li class="list-inline-item">
                    <button type="submit" class="btn btn-danger">Delete</button>            
                </li>                
            </ul>
        </div>
    </form>
    </div>
    {% endblock %}

util/templates/util/user_uploaded_document_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'util:user-uploaded-document-list' %}">User Uploaded Document Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}