social_network/urls.py
from django.urls import path

from social_network import views

app_name = 'social_network'

urlpatterns = []

urlpatterns += (
    # urls for SocialNetwork
    path('social-network/', views.SocialNetworkListView.as_view(), name='social-network-list'),
    path('social-network/create/', views.SocialNetworkCreateView.as_view(), name='social-network-create'),
    path('social-network/detail/<str:slug>/', views.SocialNetworkDetailView.as_view(), name='social-network-detail'),
    path('social-network/update/<str:slug>/', views.SocialNetworkUpdateView.as_view(), name='social-network-update'),
    path('social-network/delete/<str:slug>/', views.SocialNetworkDeleteView.as_view(), name='social-network-delete')
)

urlpatterns += (
    # urls for UserComments
    path('user-comments/', views.UserCommentsListView.as_view(), name='user-comments-list'),
    path('user-comments/create/', views.UserCommentsCreateView.as_view(), name='user-comments-create'),
    path('user-comments/detail/<str:slug>/', views.UserCommentsDetailView.as_view(), name='user-comments-detail'),
    path('user-comments/update/<str:slug>/', views.UserCommentsUpdateView.as_view(), name='user-comments-update'),
    path('user-comments/delete/<str:slug>/', views.UserCommentsDeleteView.as_view(), name='user-comments-delete')
)

urlpatterns += (
    # urls for UserLikes
    path('user-likes/', views.UserLikesListView.as_view(), name='user-likes-list'),
    path('user-likes/create/', views.UserLikesCreateView.as_view(), name='user-likes-create'),
    path('user-likes/detail/<str:slug>/', views.UserLikesDetailView.as_view(), name='user-likes-detail'),
    path('user-likes/update/<str:slug>/', views.UserLikesUpdateView.as_view(), name='user-likes-update'),
    path('user-likes/delete/<str:slug>/', views.UserLikesDeleteView.as_view(), name='user-likes-delete')
)

tsa/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static

from tsa import settings
from achievement.urls import urlpatterns as achievement_urls
from career.urls import urlpatterns as career_urls
from mentorship.urls import urlpatterns as mentoring_urls
from profile_management.urls import urlpatterns as profile_management_urls
from social_network.urls import urlpatterns as social_urls
from util.registration import urlpatterns as registration_urls
from util.site import urlpatterns as site_urls
from util.urls import urlpatterns as util_urls
from volunteer.urls import urlpatterns as volunteer_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(site_urls + registration_urls)),
    path('mentorship/', include((mentoring_urls, 'mentorship'))),
    path('util/', include((util_urls, 'util'))),
    path('achievement/', include((achievement_urls, 'achievement'))),
    path('career/', include((career_urls, 'career'))),
    path('profile_management/', include((profile_management_urls, 'profile_management'))),
    path('social_network/', include((social_urls, 'social_network'))),
    path('volunteer/', include((volunteer_urls, 'volunteer'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_network/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from util import datetime_default, text_default
from util.models import BaseModel, SoftDeleteMixin, PublishMixin


class SocialNetwork(SoftDeleteMixin):
    leader = models.ForeignKey('util.BaseUser', on_delete=models.DO_NOTHING,
                               related_name="followers_network")
    follower = models.ForeignKey('util.BaseUser', on_delete=models.DO_NOTHING,
                                 related_name="leaders_network")
    social_start = models.DateTimeField(**datetime_default)
    objects = models.Manager()

    def save(self, *args, **kwargs):
        if self.pk:
            raise RuntimeError('Cannot modify existing relationship')
        return super(SocialNetwork, self).save(*args, **kwargs)


class UserLikes(PublishMixin, BaseModel):
    like = models.BooleanField(default=True)
    rating = models.PositiveSmallIntegerField(
        help_text=_('Numeric value to rank a user. Default '
                    'range is set from 0 - 9'), default=0)
    content_object = GenericForeignKey()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveSmallIntegerField()
    user = models.ForeignKey('util.BaseUser', on_delete=models.DO_NOTHING)

    def save(self, *args, **kwargs):
        if self.rating > 10:
            self.rating = 10
        elif self.rating < 0:
            self.rating = 0
        return super(UserLikes, self).save(*args, **kwargs)


class UserComments(SoftDeleteMixin):
    comments = models.TextField(**text_default)
    user = models.ForeignKey('util.BaseUser', on_delete=models.CASCADE,
                             related_name='user_comments')
    object_id = models.PositiveSmallIntegerField()
    content_type = models.ForeignKey(ContentType, on_delete=models.DO_NOTHING)
    content_object = GenericForeignKey()

    def publish(self, **kwargs):
        return NotImplemented

social_network/forms.py
from django import forms
from social_network import models


class SocialNetworkForm(forms.ModelForm):

    def get_initial_for_field(self, field, field_name):
        # override the initial value for the specified form field
        return super(SocialNetworkForm, self).get_initial_for_field(field, field_name)

    class Meta:
        model = models.SocialNetwork
        fields = '__all__'      


class UserCommentsForm(forms.ModelForm):

    def get_initial_for_field(self, field, field_name):
        # override the initial value for the specified form field
        return super(UserCommentsForm, self).get_initial_for_field(field, field_name)

    class Meta:
        model = models.UserComments
        fields = '__all__'      


class UserLikesForm(forms.ModelForm):

    def get_initial_for_field(self, field, field_name):
        # override the initial value for the specified form field
        return super(UserLikesForm, self).get_initial_for_field(field, field_name)

    class Meta:
        model = models.UserLikes
        fields = '__all__'      

social_network/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView
from django.db.models import Q

from social_network import forms
from social_network import models
from util.views import UpdateAclMixin, DeleteAclMixin, ReadOnlyMixin


class SocialNetworkListView(ListView):
    model = models.SocialNetwork
    # paginate_by = 10
    template_name = 'social_network/social_network_list.html'

    def get_queryset(self):
        # Retrieve list object for the current user or approved user
        user = self.request.user
        if user.is_authenticated:
            queryset = super(SocialNetworkListView, self).get_queryset()
            # filter queryset for logged in user
            queryset = queryset.filter(Q(follower=user) | Q(leader=user))
            return queryset
        else:
            return super(SocialNetworkListView, self).get_queryset().none()


class SocialNetworkCreateView(LoginRequiredMixin, CreateView):
    model = models.SocialNetwork
    form_class = forms.SocialNetworkForm
    template_name = 'social_network/social_network_form.html'
    initial = {}
    login_url = reverse_lazy('user-login')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        initial = super(SocialNetworkCreateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('social_network:social_network-list')


class SocialNetworkDetailView(DetailView):
    model = models.SocialNetwork
    template_name = 'social_network/social_network_detail.html'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(SocialNetworkDetailView, self).get_context_data(**kwargs)


class SocialNetworkUpdateView(ReadOnlyMixin):
    model = models.SocialNetwork
    form_class = forms.SocialNetworkForm
    template_name = 'social_network/social_network_form.html'
    initial = {}


class SocialNetworkDeleteView(ReadOnlyMixin):
    model = models.SocialNetwork
    success_url = reverse_lazy('social_network:social-network-list')
    template_name = 'social_network/social_network_confirm_delete.html'


class UserCommentsListView(ListView):
    model = models.UserComments
    # paginate_by = 10
    template_name = 'social_network/user_comments_list.html'

    def get_queryset(self):
        # Retrieve list object for the current user or approved user
        user = self.request.user
        if user.is_authenticated:
            queryset = super(UserCommentsListView, self).get_queryset()
            # filter queryset for logged in user
            return queryset
        else:
            return super(UserCommentsListView, self).get_queryset().none()


class UserCommentsCreateView(LoginRequiredMixin, CreateView):
    model = models.UserComments
    form_class = forms.UserCommentsForm
    template_name = 'social_network/user_comments_form.html'
    initial = {}
    login_url = reverse_lazy('user-login')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        initial = super(UserCommentsCreateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('social_network:user_comments-list')


class UserCommentsDetailView(DetailView):
    model = models.UserComments
    template_name = 'social_network/user_comments_detail.html'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(UserCommentsDetailView, self).get_context_data(**kwargs)


class UserCommentsUpdateView(UpdateAclMixin):
    model = models.UserComments
    form_class = forms.UserCommentsForm
    template_name = 'social_network/user_comments_form.html'
    initial = {}
    user_field = 'user'

    def get_object(self, queryset=None):
        # Retrieve object record if current user has permission to object
        return super(UserCommentsUpdateView, self).get_object()

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('social_network:user_comments-list')

    def get_initial(self):
        initial = super(UserCommentsUpdateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial


class UserCommentsDeleteView(DeleteAclMixin):
    model = models.UserComments
    success_url = reverse_lazy('social_network:user-comments-list')
    template_name = 'social_network/user_comments_confirm_delete.html'
    user_field = 'user'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(UserCommentsDeleteView, self).get_context_data(**kwargs)


class UserLikesListView(ListView):
    model = models.UserLikes
    # paginate_by = 10
    template_name = 'social_network/user_likes_list.html'

    def get_queryset(self):
        # Retrieve list object for the current user or approved user  
        user = self.request.user
        if user.is_authenticated:
            queryset = super(UserLikesListView, self).get_queryset()
            # filter queryset for logged in user
            return queryset
        else:
            return super(UserLikesListView, self).get_queryset().none()


class UserLikesCreateView(LoginRequiredMixin, CreateView):
    model = models.UserLikes
    form_class = forms.UserLikesForm
    template_name = 'social_network/user_likes_form.html'
    initial = {}
    login_url = reverse_lazy('user-login')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        initial = super(UserLikesCreateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('social_network:user_likes-list')


class UserLikesDetailView(DetailView):
    model = models.UserLikes
    template_name = 'social_network/user_likes_detail.html'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(UserLikesDetailView, self).get_context_data(**kwargs)


class UserLikesUpdateView(UpdateAclMixin):
    model = models.UserLikes
    form_class = forms.UserLikesForm
    template_name = 'social_network/user_likes_form.html'
    initial = {}

    def get_object(self, queryset=None):
        # Retrieve object record if current user has permission to object
        return super(UserLikesUpdateView, self).get_object()

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy('user-profile', kwargs={'slug': self.request.user.urlsafe_uuid})
        else:
            return reverse_lazy('social_network:user_likes-list')

    def get_initial(self):
        initial = super(UserLikesUpdateView, self).get_initial()
        # Update initial data for instantiating form using currently logged user for queryset
        # for Many to Many and One to Many related fields
        return initial


class UserLikesDeleteView(DeleteAclMixin):
    model = models.UserLikes
    success_url = reverse_lazy('social_network:user-likes-list')
    template_name = 'social_network/user_likes_confirm_delete.html'

    def get_context_data(self, **kwargs):
        # Retrieve object record if current user has permission to object
        return super(UserLikesDeleteView, self).get_context_data(**kwargs)

social_network/templates/social_network/social_network_confirm_delete.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <form method="post">{% csrf_token %}
        <h5>Delete SocialNetwork</h5>
        <p>Are you sure you want to delete {{ object }}?</p>
        <div class="form-group">
            <ul class="list-inline">                
                <li class="list-inline-item">
                    <a href="{% url 'social_network:social-network-list' %}" class="btn btn-primary">Cancel</a>
                </li>
                <li class="list-inline-item">
                    <button type="submit" class="btn btn-danger">Delete</button>            
                </li>                
            </ul>
        </div>
    </form>
    </div>
    {% endblock %}

social_network/templates/social_network/social_network_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col">
            <a class="btn btn-primary"
               href="{% url 'social_network:social-network-list' %}">View all
            </a>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Social Network Details</h5>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-3 py-3">Relationship created on</dt>
                        <dd class="col-sm-9 py-3">{{ object.social_start }}</dd>
                        <dt class="col-sm-3 py-3">Leader</dt>
                        <dd class="col-sm-9 py-3">{{ object.leader }}</dd>
                        <dt class="col-sm-3 py-3">Follower</dt>
                        <dd class="col-sm-9 py-3">{{ object.follower }}</dd>

                    </dl>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col p-3">
            <ul class="list-inline">
                <li class="list-inline-item">
                    <a class="btn btn-primary"
                       href="{% url 'social_network:social-network-update' object.slug %}">Edit
                    </a>
                </li>

                <li class="list-inline-item">
                    <a class="btn btn-primary"
                       href="{% url 'social_network:social-network-delete' object.slug %}">Delete
                    </a>
                </li>

            </ul>
        </div>
    </div>
</div>
{% endblock %}

social_network/templates/social_network/social_network_form.html
    {% extends "base.html" %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="container my-5">
    <p>
        <a class="btn btn-primary" href="{% url 'social_network:social-network-list' %}">Social Network Listing</a>
    </p>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}

social_network/templates/social_network/social_network_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if object_list %}
<div class="container my-5">
    <div class="row">
        <div class="col">
            <div class="row my-3">
                <div class="col">
                    <h5>Social Network of {{user.public_identity}}</h5>
                </div>
            </div>
            <table class="table table-striped table-bordered table-responsive-md table-sm data-table">
                <thead class="thead-dark">
                <tr>
                    <th>Last Modified At</th>
                    <th>Created At</th>
                    <th>Social Start</th>
                    <th>Follower</th>
                    <th>Leader</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                <tr>
                    <!-- Rendered content with action buttons -->
                    <td>{{object.last_modified_at}}</td>
                    <td>{{object.created_at}}</td>
                    <td>{{object.social_start}}</td>
                    <td>{{object.follower}}</td>
                    <td>{{object.leader}}</td>
                    <td>
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <a href="{% url 'social_network:social-network-detail' object.slug %}" class="cmd
                cmd-detail" data-toggle="tooltip" title="View"><i class="fa fa-search-plus">&nbsp;</i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'social_network:social-network-update' object.slug %}"
                                   class="cmd cmd-edit" data-toggle="tooltip"
                                   title="Edit">
                                    <i class="fa fa-edit">&nbsp;</i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'social_network:social-network-delete' object.slug %}" class="cmd
            cmd-delete" data-toggle="tooltip" title="Delete"><i class="fa fa-trash">&nbsp;</i>
                                </a>
                            </li>
                        </ul>
                    </td>

                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-12">

            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <h5>No record exists for selected entity</h5>
                <p>You may create new record using the ADD command </p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="col">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="btn btn-primary"
                           href="{% url 'social_network:social-network-create' %}">Add</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn btn-primary"
                           href="{{ request.META.HTTP_REFERER }}">
                            Back
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

social_network/templates/social_network/user_comments_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <div class="container my-5">
        <div class="row">
            <div class="col">
                <a class="btn btn-primary"
                   href="{% url 'social_network:user-comments-list' %}">View All UserComments
                </a>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">UserComments Details</h5>
                    </div>
                    <div class="card-body">
                        <dl class="row"><dt class="col-sm-3 py-3">Achievements</dt><dd class="col-sm-9 py-3">{{ object.achievements }}</dd><dt class="col-sm-3 py-3">Education History</dt><dd class="col-sm-9 py-3">{{ object.education_history }}</dd><dt class="col-sm-3 py-3">Qualification</dt><dd class="col-sm-9 py-3">{{ object.qualification }}</dd><dt class="col-sm-3 py-3">Content Type</dt><dd class="col-sm-9 py-3">{{ object.content_type }}</dd><dt class="col-sm-3 py-3">Content Object</dt><dd class="col-sm-9 py-3">{{ object.content_object }}</dd><dt class="col-sm-3 py-3">Work Experience</dt><dd class="col-sm-9 py-3">{{ object.work_experience }}</dd><dt class="col-sm-3 py-3">Object Id</dt><dd class="col-sm-9 py-3">{{ object.object_id }}</dd><dt class="col-sm-3 py-3">Created At</dt><dd class="col-sm-9 py-3">{{ object.created_at }}</dd><dt class="col-sm-3 py-3">Comments</dt><dd class="col-sm-9 py-3">{{ object.comments }}</dd><dt class="col-sm-3 py-3">User</dt><dd class="col-sm-9 py-3">{{ object.user }}</dd><dt class="col-sm-3 py-3">Last Modified At</dt><dd class="col-sm-9 py-3">{{ object.last_modified_at }}</dd><dt class="col-sm-3 py-3">Academic Graduation</dt><dd class="col-sm-9 py-3">{{ object.academic_graduation }}</dd></dl>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row mt-4">
            <div class="col p-3">
            <ul class="list-inline">
            <li class="list-inline-item">
                <a class="btn btn-primary" 
                    href="{% url 'social_network:user-comments-update' object.slug %}">Edit
                </a>
            </li>
    
            <li class="list-inline-item">
                <a class="btn btn-primary"
                   href="{% url 'social_network:user-comments-delete' object.slug %}">Delete
                </a>
            </li>
    
            </ul>            
            </div>
        </div>
    </div>
    {% endblock %}

social_network/templates/social_network/user_comments_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if object_list %}
    <div class="container my-5">
    <div class="row">
        <div class="col">    
            <table class="table table-striped table-bordered table-responsive table-sm data-table">
                <thead class="thead-dark">
                <tr><th>Achievements</th><th>Education History</th><th>Qualification</th><th>Content Type</th><th>Content Object</th><th>Work Experience</th><th>Object Id</th><th>Created At</th><th>Comments</th><th>User</th><th>Last Modified At</th><th>Academic Graduation</th><th>Actions</th></tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <!-- Rendered content with action buttons -->
                        <td>{{object.achievements}}</td><td>{{object.education_history}}</td><td>{{object.qualification}}</td><td>{{object.content_type}}</td><td>{{object.content_object}}</td><td>{{object.work_experience}}</td><td>{{object.object_id}}</td><td>{{object.created_at}}</td><td>{{object.comments}}</td><td>{{object.user}}</td><td>{{object.last_modified_at}}</td><td>{{object.academic_graduation}}</td>
<td>
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="{% url 'social_network:user-comments-detail' object.slug %}" class="cmd 
                cmd-detail" data-toggle="tooltip" title="View"><i class="fa fa-search-plus">&nbsp;</i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{% url 'social_network:user-comments-update' object.slug %}" class="cmd cmd-edit" data-toggle="tooltip" 
title="Edit">
                <i class="fa fa-edit">&nbsp;</i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{% url 'social_network:user-comments-delete' object.slug %}" class="cmd 
            cmd-delete" data-toggle="tooltip" title="Delete"><i class="fa fa-trash">&nbsp;</i>
            </a>
        </li>
    </ul>
</td>
                        
                    </tr>
                {% endfor %}        
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-12">

            <div class="alert alert-info alert-dismissible fade show" role="alert">
               <h5>No record exists for selected entity</h5>
              <p>You may create new record using the ADD command </p>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="col">                    
               <ul class="list-inline">
                  <li class="list-inline-item">
                    <a class="btn btn-primary" 
                    href="{% url 'social_network:user-comments-create' %}" >Add</a>
                  </li>
                  <li class="list-inline-item">
                    <a class="btn btn-primary" 
                        href="{{ request.META.HTTP_REFERER }}">
                        Back
                    </a>
                  </li>                      
                </ul>                    
            </div>          
        </div>        
    </div>
    </div>
    {% endif %}
    {% endblock %}

social_network/templates/social_network/user_likes_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if object_list %}
    <div class="container my-5">
    <div class="row">
        <div class="col">    
            <table class="table table-striped table-bordered table-responsive table-sm data-table">
                <thead class="thead-dark">
                <tr><th>Object Id</th><th>Content Type</th><th>User</th><th>Member</th><th>Like</th><th>Content Object</th><th>Rating</th><th>Actions</th></tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <!-- Rendered content with action buttons -->
                        <td>{{object.object_id}}</td><td>{{object.content_type}}</td><td>{{object.user}}</td><td>{{object.member}}</td><td>{{object.like}}</td><td>{{object.content_object}}</td><td>{{object.rating}}</td>
<td>
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="{% url 'social_network:user-likes-detail' object.slug %}" class="cmd 
                cmd-detail" data-toggle="tooltip" title="View"><i class="fa fa-search-plus">&nbsp;</i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{% url 'social_network:user-likes-update' object.slug %}" class="cmd cmd-edit" data-toggle="tooltip" 
title="Edit">
                <i class="fa fa-edit">&nbsp;</i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{% url 'social_network:user-likes-delete' object.slug %}" class="cmd 
            cmd-delete" data-toggle="tooltip" title="Delete"><i class="fa fa-trash">&nbsp;</i>
            </a>
        </li>
    </ul>
</td>
                        
                    </tr>
                {% endfor %}        
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-12">

            <div class="alert alert-info alert-dismissible fade show" role="alert">
               <h5>No record exists for selected entity</h5>
              <p>You may create new record using the ADD command </p>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="col">                    
               <ul class="list-inline">
                  <li class="list-inline-item">
                    <a class="btn btn-primary" 
                    href="{% url 'social_network:user-likes-create' %}" >Add</a>
                  </li>
                  <li class="list-inline-item">
                    <a class="btn btn-primary" 
                        href="{{ request.META.HTTP_REFERER }}">
                        Back
                    </a>
                  </li>                      
                </ul>                    
            </div>          
        </div>        
    </div>
    </div>
    {% endif %}
    {% endblock %}